export const videoTube = [
  {
    id: 1,
    name: "El Chavo Animado *La Casa del Árbol*",
    video: "https://www.youtube.com/embed/9U4LhNCjVPU",
    category: "infantil",
  },
  {
    id: 2,
    name: "El juego  del CALAMAR en halloween *Desocupe masivo*",
    video: "https://www.youtube.com/embed/OSASr0-FUQk",
    category: "infantil",

  },
  {
    id: 3,
    name: "Curso JavaScript: Callbacks - #jonmircha",
    video: "https://www.youtube.com/embed/TYG2_iUr8XY",
    category: "programacion",
  },
  {
    id: 4,
    name: "Homero roba con un Parquimetro *Los simpsons*",
    video: "https://www.youtube.com/embed/FOFPh_dAg6g",
    category: "infantil",
  },
  {
    id: 5,
    name: "Cuidate del hombre Coop",
    video: "https://www.youtube.com/embed/YROXZU8oZU4",
    category: "infantil",
  },
  {
    id: 6,
    name: "Formulario animado con HTML, CSS y Javascript",
    video: "https://www.youtube.com/embed/iN0xYdgRAzk",
    category: "programacion",
  },
  {
    id: 7,
    name: " GLUTEOS, ABDOMEN,PIERNAS Y BRAZOS",
    video: "https://www.youtube.com/embed/AUTqIj21X7g",
    category: "entrenamiento",
  },
  {
    id: 8,
    name: "Activa tu celebro al 100% con este test de VELOCIDAD MENTAL",
    video: "https://www.youtube.com/embed/YYCQP5FKGsM",
    category: "entrenamiento",
  },
  {
    id: 9,
    name: "Si tienes pasta en casa, ¡haz esta deliciosa receta que a todos les encantará!",
    video: "https://www.youtube.com/embed/hV2x9wjJ3I8",
    category: "resetas",
  },
  {
    id: 10,
    name: "15 PLANTAS QUE PUEDES CULTIVAR FÁCILMENTE EN TU PROPIA COCINA",
    video: "https://www.youtube.com/embed/S5a3cCXvmGc",
    category: "resetas",
  },
  {
    id: 11,
    name: "Cómo cuidar las plantas de manera correcta *Desocupe Masivo*",
    video: "https://www.youtube.com/embed/l08CTff43k8",
    category: "resetas",
  },
  {
    id: 12,
    name: "Birria de Res | La Capital",
    video: "https://www.youtube.com/embed/g2F5RO6vNSs",
    category: "resetas",
  },
  {
    id: 13,
    name: "EL CABO DE LA VELA 🪁viaje en mot por la GUAJIRA",
    video: "https://www.youtube.com/embed/Q5J6eImVS5g",
    category: "viajes",
  },
  {
    id: 14,
    name: "Arrays y Objetos en JavaScript en 15 Minutos",
    video: "https://www.youtube.com/embed/5DaZXXbHI_U",
    category: "programacion",
  },
  {
    id: 15,
    name: "Curso Basico de CSS, Selectores",
    video: "https://www.youtube.com/embed/uqkj7HQ7ids",
    category: "programacion.",
  },
  {
    id: 16,
    name: "Masha y el Oso",
    video: "https://www.youtube.com/embed/i-vgTAPcSas",
    category: "infantil.",
  },
  {
    id: 17,
    name: "Comidas rapidas y faciles de hacer",
    video: "https://www.youtube.com/embed/vRu7yWotnws",
    category: "recestas.",
  },
  {
    id: 18,
    name: "Pollo a la cocacola",
    video: "https://www.youtube.com/embed/L5Tfja6mZDY",
    category: "recetas.",
  },
  {
    id: 19,
    name: "El viaje que no creí hacer jamás |La Polinesia Francesa",
    video: "https://www.youtube.com/embed/yi8h9V5duFI",
    category: "Viajes.",
  },
  {
    id: 20,
    name: "Tom y Jerry| ¡Un poco de aire fresco! ",
    video: "https://www.youtube.com/embed/WJUsTx2cfe4",
    category: "programacion.",
  },
];
