export const videoTube = [
  {
    id: 1,
    name: "El Chavo Animado",
    video: "https://www.youtube.com/embed/9U4LhNCjVPU",
    category: "infantil",
    img: "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/8858c0a9d5c57f8056b4f58ce161eb39e5b930afd53c3d8ef73aef5724d56114._RI_V_TTW_.jpg",
  },
  {
    id: 2,
    name: "El juego  del CALAMAR *Desocupe masivo*",
    video: "https://www.youtube.com/embed/OSASr0-FUQk",
    category: "infantil",
    img: "https://i.ytimg.com/vi/OSASr0-FUQk/maxresdefault.jpg",
  },
  {
    id: 3,
    name: "Curso JavaScript: Callbacks - #jonmircha",
    video: "https://www.youtube.com/embed/TYG2_iUr8XY",
    category: "programacion",
    img: "https://i.ytimg.com/vi/TYG2_iUr8XY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCiimRwQlo2zx7ReZt_R72x1cc_HQ",
  },
  {
    id: 4,
    name: "Homero roba con un Parquimetro *Los simpsons*",
    video: "https://www.youtube.com/embed/FOFPh_dAg6g",
    category: "infantil",
    img: "https://i.ytimg.com/vi/B53H_rAVJeo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCfYwbmNLXBAbV0y7h6wiWKjO19_Q",
  },
  {
    id: 5,
    name: "Cuidate del hombre Coop",
    video: "https://www.youtube.com/embed/YROXZU8oZU4",
    category: "infantil",
    img: "https://i.ytimg.com/vi/YROXZU8oZU4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBxhvzmWh6SXrLOa-bHGcaUf_MjZQ",
  },
  {
    id: 6,
    name: "Formulario animado con HTML, CSS y Javascript",
    video: "https://www.youtube.com/embed/iN0xYdgRAzk",
    category: "programacion",
    img: "https://i.ytimg.com/vi/iN0xYdgRAzk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvrsf6if0VS0GVgF7qVL77D4mZFg",
  },
  {
    id: 7,
    name: "Si tienes pasta en casa, ¡haz esta deliciosa receta!",
    video: "https://www.youtube.com/embed/hV2x9wjJ3I8",
    category: "resetas",
    img: "https://i.ytimg.com/vi/hV2x9wjJ3I8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC5V-Y6MjKOV-Ytysgzvz42RrjM2A",
  },
  {
    id: 8,
    name: "15 plantas que puedes cultivar facil en tu casa",
    video: "https://www.youtube.com/embed/S5a3cCXvmGc",
    category: "resetas",
    img: "https://i.ytimg.com/vi/S5a3cCXvmGc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDSW9LY58Qumo29N5YostAT2KctFA",
  },
  {
    id: 9,
    name: "Cómo cuidar las plantas de manera correcta *Desocupe Masivo*",
    video: "https://www.youtube.com/embed/l08CTff43k8",
    category: "resetas",
    img: "https://i.ytimg.com/vi/l08CTff43k8/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBu11bsHlrVspRHGuwfvs2dmOSz6w",
  },
  {
    id: 10,
    name: "Birria de Res | La Capital",
    video: "https://www.youtube.com/embed/g2F5RO6vNSs",
    category: "resetas",
    img: "https://i.ytimg.com/vi/g2F5RO6vNSs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByfo_ycEI5ICsvjGo4To9mWMxOIA",
  },
  {
    id: 11,
    name: "EL CABO DE LA VELA 🪁viaje en mot por la GUAJIRA",
    video: "https://www.youtube.com/embed/Q5J6eImVS5g",
    category: "viajes",
    img: "https://i.ytimg.com/vi/Q5J6eImVS5g/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA4TnPxijBnnvWDpPtlBtra2aZBDA",
  },
  {
    id: 12,
    name: "Arrays y Objetos en JavaScript en 15 Minutos",
    video: "https://www.youtube.com/embed/5DaZXXbHI_U",
    category: "programacion",
    img: "https://i.ytimg.com/vi/5DaZXXbHI_U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAWiuulfwgp-JJhl_gLfl6f2Vha3Q",
  },
  {
    id: 13,
    name: "Curso Basico de CSS, Selectores",
    video: "https://www.youtube.com/embed/uqkj7HQ7ids",
    category: "programacion.",
    img: "https://i.ytimg.com/vi/24gNhTcy6pw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDZFUB3j81hPh5ZfjFcxDgYfYsSpQ",
  },
  {
    id: 14,
    name: "Masha y el Oso",
    video: "https://www.youtube.com/embed/i-vgTAPcSas",
    category: "infantil.",
    img: "https://i.ytimg.com/vi/i-vgTAPcSas/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCfk45o-n458p-Er_cyZRNukD5qrw",
  },
  {
    id: 15,
    name: "Comidas rapidas y faciles de hacer",
    video: "https://www.youtube.com/embed/vRu7yWotnws",
    category: "recestas.",
    img: "https://i.ytimg.com/vi/vRu7yWotnws/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDsU1VQrd7FgYBP8ampae5_-bG9Sg",
  },
  {
    id: 16,
    name: "Pollo a la cocacola",
    video: "https://www.youtube.com/embed/L5Tfja6mZDY",
    category: "recetas.",
    img: "https://i.ytimg.com/vi/L5Tfja6mZDY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAZFxAilKMF-SUZDR5hvYPHEqjRNA",
  },
  {
    id: 17,
    name: "El viaje que no creí hacer jamás |La Polinesia Francesa",
    video: "https://www.youtube.com/embed/yi8h9V5duFI",
    category: "Viajes.",
    img: "https://i.ytimg.com/vi/yi8h9V5duFI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHlohFquq2yNSQK9EhQ8TT4b7-HA",
  },
  {
    id: 18,
    name: "Tom y Jerry| ¡Un poco de aire fresco! ",
    video: "https://www.youtube.com/embed/WJUsTx2cfe4",
    category: "infantil.",
    img: "https://i.ytimg.com/vi/WJUsTx2cfe4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWJWHT8GmBJqTzrxMbRpH3gJiC2Q",
  },
  {
    id: 19,
    name: "El Pájaro Loco",
    video: "https://www.youtube.com/embed/ONM5bXQ2dNw",
    category: "infantil.",
    img: "https://i.ytimg.com/vi/ONM5bXQ2dNw/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLApJn7c2gThxQRMRu24zyLIgF8xaQ",
  },
  {
    id: 20,
    name: "Como hacer muslo de pollo",
    video: "https://www.youtube.com/embed/qk-jV61NYRQ",
    category: "infantil.",
    img: "https://i.ytimg.com/vi/qk-jV61NYRQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzEFPnad992R4aax22NRQNih6RAg",
  },
];
